site_name: Yxène

theme:
  name: material
  icon:
    logo: fontawesome/regular/flag
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: indigo

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: amber
      accent: amber
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: README.md
  - Writeupss:
    - Overview: writeupss/README.md
    - TryHackMe:
      - Overwiew: writeupss/tryhackme/README.md
      - Valley: writeupss/tryhackme/valley/README.md
      - RootMe: writeupss/tryhackme/rootme/README.md
      - Cheese CTF: writeupss/tryhackme/cheese-ctf/README.md
      - Agent Sudo: writeupss/tryhackme/agent-sudo/README.md
      - Startup: writeupss/tryhackme/startup/README.md
    - FCSC:
      - Overwiew: writeupss/fcsc/README.md
      - Petite Frappe: writeupss/fcsc/petite-frappe/README.md
      - Layer Cake: writeupss/fcsc/layer-cake/README.md
      - Meme Generator: writeupss/fcsc/meme-generator/README.md
      - CryptoLocker v1: writeupss/fcsc/cryptolocker-v1/README.md
    - UnitedCTF:
      - Overwiew: writeupss/unitedctf/README.md
      - ARPacadabra: writeupss/unitedctf/arpacadabra/README.md
    - CryptoHack:
      - Overwiew: writeupss/cryptohack/README.md
      - JSON in JSON: writeupss/cryptohack/json-in-json/README.md

