site_name: Yxène

theme:
  name: material
  icon:
    logo: fontawesome/regular/flag
  palette:

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: indigo

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
      primary: amber
      accent: amber
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: README.md
  - Writeups:
    - writeups/index.md
    - TryHackMe:
      - writeups/tryhackme/index.md
      - Valley: writeups/tryhackme/valley/README.md
      - RootMe: writeups/tryhackme/rootme/README.md
      - Cheese CTF: writeups/tryhackme/cheese-ctf/README.md
      - Agent Sudo: writeups/tryhackme/agent-sudo/README.md
      - Startup: writeups/tryhackme/startup/README.md
    - FCSC:
      - writeups/fcsc/index.md
      - Petite Frappe: writeups/fcsc/petite-frappe/README.md
      - Layer Cake: writeups/fcsc/layer-cake/README.md
      - Meme Generator: writeups/fcsc/meme-generator/README.md
      - CryptoLocker v1: writeups/fcsc/cryptolocker-v1/README.md
    - UnitedCTF:
      - writeups/unitedctf/index.md
      - ARPacadabra: writeups/unitedctf/arpacadabra/README.md
    - CryptoHack:
      - writeups/cryptohack/index.md
      - JSON in JSON: writeups/cryptohack/json-in-json/README.md
  - My Challenges:
    - my-challenges/index.md
    - 24@CTF 2024:
      - OSINT:
        - SteganOsint 1: my-challenges/24hctf-2024/osint/steganosint-1/README.md
        - SteganOsint 2: my-challenges/24hctf-2024/osint/steganosint-2/README.md
        - Sur les traces de Scofield 1: my-challenges/24hctf-2024/osint/sur-les-traces-de-scofield-1/README.md
        - Sur les traces de Scofield 2: my-challenges/24hctf-2024/osint/sur-les-traces-de-scofield-2/README.md
        - Sur les traces de Scofield 3: my-challenges/24hctf-2024/osint/sur-les-traces-de-scofield-3/README.md
    - UnitedCTF 2024:
      - Programming:
        - Fortune L33t3r 1: my-challenges/unitedctf-2024/programming/fortune-l33t3r-1/README.md
        - Fortune L33t3r 2: my-challenges/unitedctf-2024/programming/fortune-l33t3r-2/README.md
    - Mois de la cyber 2024:
      - OSINT:
        - Katherin Stallings a disparu 1: my-challenges/mois-de-la-cyber-2024/osint/katherin-stallings-a-disparu-1/README.md
        - Katherin Stallings a disparu 2: my-challenges/mois-de-la-cyber-2024/osint/katherin-stallings-a-disparu-2/README.md
        - Katherin Stallings a disparu 3: my-challenges/mois-de-la-cyber-2024/osint/katherin-stallings-a-disparu-3/README.md
    - h0h0h0day CTF 2024:
      - Steganography:
        - Dialing To Merry Festivities: my-challenges/h0h0h0day-ctf-2024/steganography/dialing-to-merry-festivities/README.md
    - PolyPwn 2025:
      - Network:
        - TitaNIC: my-challenges/polypwn-2025/network/titanic/README.md

